# Práctica 04: Análisis Exploratorio de Datos con Python y Jupyter Notebook

**Programa de estudios:** Ingeniería en Desarrollo y Gestión de Software <br>
**Asignatura:** Extracción de Conocimiento en Bases de Datos <br>
**Docente:** M.T.I. Marco A. Ramírez Hernández <br>
**Periodo:** Mayo - Agosto 2026 <br>

---
## Unidad 2: Preparacion de los Datos:

**Nombre del estudiante:** Derek Sesni Carreño <br>
**Matricula:** 230892 <br>
**Grado y Grupo:** 9 A IDGS <br>

El estudiante  practicara como realizar un analisis de datos, utilizando el lenguaje de proggramacion de Python y Librerias comunes para la cargam 
manipulacion, analisis y visualizacion previa de un conjunto de datos (Dataset), para esta practica se utilizaran las librerias de:

- Pandas
- Numby
- Seaborn
- os
- Matloip

1. Importar las librerias necesarias para realizar el EDA:

Comenzamos por importar la libreria que nos permitira manipular los datos del dataset extraidos de una duente de datos (datasource)

In [7]:
import pandas as pd

2. Creamos un DataFrame. leyendo el archivo delimitado por (.CSC)

In [54]:
pokemon=pd.read_csv('./Pokemon.csv')

3. Imprimimos el resultado de la lectura

Este comando imprime en una tabla de las comluimunas y las filas del dataframe, siempre de manera estandar nos mostrara los 5 primeros y 5 uultimos del dataframe

In [55]:
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
3,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
4,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
798,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
799,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
800,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
801,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
802,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

4. Obetener una muestra aleatoria de registros del dataframe usando el nediti **.sample**

In [15]:
pokemon.sample(7) ## toma 5 datos aleatorios de la lista

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
385,353,Shuppet,Ghost,NaN,295,44,75,35,63,33,45,3,False
194,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
442,397,Staravia,Normal,Flying,340,55,75,50,40,40,80,4,False
135,126,Magmar,Fire,NaN,495,65,95,57,100,85,93,1,False
471,424,Ambipom,Normal,NaN,482,75,100,66,60,66,115,4,False
699,638,Cobalion,Steel,Fighting,580,91,90,129,90,72,108,5,True
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False

**Ejercicio 1 :** Obten una muestra de 50 pokemones

In [16]:
pokemon.sample(50) ## toma 5 datos aleatorios de la lista

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
739,671,Florges,Fairy,NaN,552,78,65,68,112,154,75,6,False
446,401,Kricketot,Bug,NaN,194,37,25,41,25,41,25,4,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
377,345,Lileep,Rock,Grass,355,66,41,77,61,87,23,3,False
780,710,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False
58,53,Persian,Normal,NaN,440,65,70,60,65,65,115,1,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
530,478,Froslass,Ice,Ghost,480,70,80,70,80,70,110,4,False
568,509,Purrloin,Dark,NaN,281,41,50,37,50,37,66,5,False
402,367,Huntail,Water,NaN,485,55,104,105,94,75,52,3,False
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False
727,659,Bunnelby,Normal,NaN,237,38,36,38,32,36,57,6,False
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
399,364,Sealeo,Ice,Water,410,90,60,70,75,70,45,3,False
602,542,Leavanny,Bug,Grass,500,75,103,80,70,80,92,5,False
116,108,Lickitung,Normal,NaN,385,90,55,75,60,75,30,1,False
668,607,Litwick,Ghost,Fire,275,50,30,55,65,55,20,5,False
595,535,Tympole,Water,NaN,294,50,50,40,50,40,64,5,False
237,219,Magcargo,Fire,Rock,410,50,50,120,80,80,30,2,False
233,215,Sneasel,Dark,Ice,430,55,95,55,35,75,115,2,False
271,251,Celebi,Psychic,Grass,600,100,100,100,100,100,100,2,False
492,444,Gabite,Dragon,Ground,410,68,90,65,50,55,82,4,False
390,357,Tropius,Grass,Flying,460,99,68,83,72,87,51,3,False
128,119,Seaking,Water,NaN,450,80,92,65,65,80,68,1,False
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
590,531,Audino,Normal,NaN,445,103,60,86,60,86,50,5,False
325,301,Delcatty,Normal,NaN,380,70,65,65,55,55,70,3,False
503,453,Croagunk,Poison,Fighting,300,48,61,40,61,40,50,4,False
302,279,Pelipper,Water,Flying,430,60,50,100,85,70,65,3,False
221,206,Dunsparce,Normal,NaN,415,100,70,70,65,65,45,2,False
285,262,Mightyena,Dark,NaN,420,70,90,70,60,60,70,3,False
732,664,Scatterbug,Bug,NaN,200,38,35,40,27,25,35,6,False
194,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
104,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
79,73,Tentacruel,Water,Poison,515,80,70,65,80,120,100,1,False
561,502,Dewott,Water,NaN,413,75,75,60,83,60,60,5,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
608,548,Petilil,Grass,NaN,280,45,35,50,70,50,30,5,False
257,238,Smoochum,Ice,Psychic,305,45,30,15,85,65,65,2,False
685,624,Pawniard,Dark,Steel,340,45,85,70,40,40,60,5,False
38,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False
505,455,Carnivine,Grass,NaN,454,74,100,72,90,72,46,4,False
265,246,Larvitar,Rock,Ground,300,50,64,50,45,50,41,2,False
337,309,Electrike,Electric,NaN,295,40,45,40,65,40,65,3,False
144,133,Eevee,Normal,NaN,325,55,55,50,45,65,55,1,False
547,489,Phione,Water,NaN,480,80,80,80,80,80,80,4,False

5. Obtener una muestra de rangos definidos usando **.iloc**

In [17]:
pokemon_100_to_200 = pokemon.iloc[100:200]
pokemon_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
103,95,Onix,Rock,Ground,385,35,45,160,30,45,70,1,False
104,96,Drowzee,Psychic,NaN,328,60,48,45,43,90,42,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
198,183,Marill,Water,Fairy,250,70,20,50,20,50,40,2,False
199,184,Azumarill,Water,Fairy,420,100,50,80,60,80,50,2,False

6. Como saber las columnas o atributos tiene un dataframe

In [19]:
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

Campo Descripcion <br>
**#** El ID o numero de identificacion del Pokemo
**Name:** El nombre del Pokémon <br>
**Type 1:** Se refiere a las partes elementales (tipos) asociados tanto al Pokémon como a sus movimientos. <br>
**Type 2:** Los Pokémon pueden tener hasta 2 tipos (Pokémon de tipo dual); los movimientos solo pueden tener uno. <br>
**Total:** Representa la suma de todos los stats, lo que te da una idea de qué tan “pesado” o fuerte es el Pokémon. <br>
**HP** (Puntos de Salud): Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaya). <br>
**Attack:** La fuerza física de los ataques del Pokémon. <br>
**Defense:** Qué tanto aguanta el Pokémon contra los ataques físicos del rival. <br>
**Sp. Atk:** Ataque Especial; el poder de los movimientos especiales del Pokémon. <br>
**Sp. Def:** Defensa Especial; qué tan resistente es el Pokémon ante los ataques especiales. <br>
**Speed** (Velocidad): El Pokémon que tenga más velocidad ataca primero. <br>
**Generations:** Se refiere a la generación de la serie de juegos a la que pertenece. <br>
**Legendary:** Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano (sí/no). <br>

7. Explorar la composicion y ausencia de datos (METADATA) con **.info**

La libreria de pandas, incluye un metodo que nos permite el tipo de datos y ausencia

In [22]:
pokemon.info

<bound method DataFrame.info of        #                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49
1      2                Ivysaur    Grass  Poison    405  60      62       63
2      3               Venusaur    Grass  Poison    525  80      82       83
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123
4      4             Charmander     Fire     NaN    309  39      52       43
..   ...                    ...      ...     ...    ...  ..     ...      ...
795  719                Diancie     Rock   Fairy    600  50     100      150
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
799  721              Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         80       80     60           1      False
2        100      100     80           1      False
3        122      120     80           1      False
4         60       50     65           1      False
..       ...      ...    ...         ...        ...
795      100      150     50           6       True
796      160      110    110           6       True
797      150      130     70           6       True
798      170      130     80           6       True
799      130       90     70           6       True

[800 rows x 13 columns]>

8. Limpieza de datos

Dependiendo del objetivo del analisis de algunas columnas o registri no seran necesartas en nuestro dataframe, en este caso ominiremos los datos vacios , por los que
eliminaremos la comlumna 'Type 2' y renombraremos la comunna 'Type 1' por 'Type'

In [29]:
del pokemon ['Type 2']
pokemon = pokemon.rename(columns={'Type 1': 'Type'})

KeyError: 'Type 2'

pokemon

In [ ]:
**Ejercicio 02** Consulta la METADARA de la actualizacion

9. Visualizacion de os primeros datos usando el metodo **.head**

In [ ]:
Ejercicio 03 Muestra los ultimos 10 registros del dataframe

10. Estadistica basudaca del dataframe

Pandas permite emitir un reporte de estadistica basica (nedidas de tendencia) sobre datos cuantitativos

In [33]:
pokemon.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

11. Calcular el total de datos no puplicados (unicos) <br>
Usaremos **.len()** como funcion para calcular la longitud del dataset y **unique** para excluir los duplicados

 ***NOTA:*** No conciderar ID como un atributo de llave primaria, sino el total de columnas con un solo elemento u objeto.

Obteniendo los valores unicos por columna en este caso en la comlumna "Name"

In [58]:
len(pokemon.Name.unique())

800

Obteniendo el total de objetos (Conjunto de atributos, estrictamente iguales) , unicos

In [60]:
total_unicos = len(pokemon.drop_duplicates())
total_unicos

801

**Ejercicio 04** Obtener el total de IDs unicos en el dataset

In [71]:
total_unicos = pokemon'#'.nunique()

SyntaxError: invalid syntax (3677380524.py, line 1)

**Ejercicios 05:** Obtener el total tipos unicos de pokemon

12. Contabilizacion de Datos por Atributo

 Pandas nos permite agrupar los datos por atributos y contabilizar los totales usando .value_counts() <br>
¿Cuantos Pokemones hay por generaciom?

In [73]:
pokemon['Generation'].value_counts()

Generation
1    169
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64