# Práctica 04: Análisis Exploratorio de Datos con Python y Jupyter Notebook

**Programa de estudios:** Ingeniería en Desarrollo y Gestión de Software <br>
**Asignatura:** Extracción de Conocimiento en Bases de Datos <br>
**Docente:** M.T.I. Marco A. Ramírez Hernández <br>
**Periodo:** Mayo - Agosto 2026 <br>

---
## Unidad 2: Preparacion de los Datos:

**Nombre del estudiante:** Derek Sesni Carreño <br>
**Matricula:** 230892 <br>
**Grado y Grupo:** 9 A IDGS <br>

El estudiante  practicara como realizar un analisis de datos, utilizando el lenguaje de proggramacion de Python y Librerias comunes para la cargam 
manipulacion, analisis y visualizacion previa de un conjunto de datos (Dataset), para esta practica se utilizaran las librerias de:

- Pandas
- Numby
- Seaborn
- os
- Matloip

1. Importar las librerias necesarias para realizar el EDA:

Comenzamos por importar la libreria que nos permitira manipular los datos del dataset extraidos de una duente de datos (datasource)

In [7]:
import pandas as pd

2. Creamos un DataFrame. leyendo el archivo delimitado por (.CSC)

In [8]:
pokemon=pd.read_csv('./Pokemon.csv')

3. Imprimimos el resultado de la lectura

Este comando imprime en una tabla de las comluimunas y las filas del dataframe, siempre de manera estandar nos mostrara los 5 primeros y 5 uultimos del dataframe

In [9]:
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
3,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
4,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
798,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
799,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
800,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
801,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
802,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

4. Obetener una muestra aleatoria de registros del dataframe usando el nediti **.sample**

In [10]:
pokemon.sample(7) ## toma 5 datos aleatorios de la lista

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
271,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
219,201,Unown,Psychic,NaN,336,48,72,48,72,48,48,2,False
668,604,Eelektross,Electric,NaN,515,85,115,80,105,80,50,5,False
45,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
283,258,Mudkip,Water,NaN,310,50,70,50,50,50,40,3,False
394,358,Chimecho,Psychic,NaN,425,65,50,70,95,80,65,3,False
687,623,Golurk,Ground,Ghost,483,89,124,80,55,80,55,5,False

**Ejercicio 1 :** Obten una muestra de 50 pokemones

In [11]:
pokemon.sample(50) ## toma 5 datos aleatorios de la lista

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
18,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
545,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,True
488,437,Bronzong,Steel,Psychic,500,67,89,116,79,116,33,4,False
564,502,Dewott,Water,NaN,413,75,75,60,83,60,60,5,False
259,237,Hitmontop,Fighting,NaN,455,50,95,95,35,110,70,2,False
312,285,Shroomish,Grass,NaN,295,60,40,60,40,60,35,3,False
683,619,Mienfoo,Fighting,NaN,350,45,85,50,55,50,65,5,False
242,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
44,36,Clefable,Fairy,NaN,483,95,70,73,95,90,60,1,False
36,28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,1,False
344,312,Minun,Electric,NaN,405,60,40,50,75,85,95,3,False
789,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
633,569,Garbodor,Poison,NaN,474,80,95,82,60,82,75,5,False
124,113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
16,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
173,156,Quilava,Fire,NaN,405,58,64,58,80,65,80,2,False
570,508,Stoutland,Normal,NaN,500,85,110,90,45,90,80,5,False
309,282,GardevoirMega Gardevoir,Psychic,Fairy,618,68,85,65,165,135,100,3,False
303,277,Swellow,Normal,Flying,430,60,85,60,50,50,125,3,False
422,381,Latios,Dragon,Psychic,600,80,90,80,130,110,110,3,True
41,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False
302,276,Taillow,Normal,Flying,270,40,55,30,30,30,85,3,False
2,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
188,171,Lanturn,Water,Electric,460,125,58,58,76,76,67,2,False
147,133,Eevee,Normal,NaN,325,55,55,50,45,65,55,1,False
450,402,Kricketune,Bug,NaN,384,77,85,51,55,51,65,4,False
28,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
282,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
716,647,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
737,666,Vivillon,Bug,Flying,411,80,52,50,90,50,89,6,False
214,196,Espeon,Psychic,NaN,525,65,65,60,130,95,110,2,False
777,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False
689,625,Bisharp,Dark,Steel,490,65,125,100,60,70,70,5,False
754,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
49,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
533,478,Froslass,Ice,Ghost,480,70,80,70,80,70,110,4,False
397,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False
233,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False
234,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
707,642,ThundurusIncarnate Forme,Electric,Flying,580,79,115,70,125,80,111,5,True
447,399,Bidoof,Normal,NaN,250,59,45,40,35,40,31,4,False
585,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
362,328,Trapinch,Ground,NaN,290,45,100,45,45,45,10,3,False
68,60,Poliwag,Water,NaN,300,40,50,40,40,40,90,1,False
7,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
192,175,Togepi,Fairy,NaN,245,35,20,65,40,65,20,2,False
425,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
316,289,Slaking,Normal,NaN,670,150,160,100,95,65,100,3,False
185,168,Ariados,Bug,Poison,390,70,90,70,60,60,40,2,False
85,76,Golem,Rock,Ground,495,80,120,130,55,65,45,1,False

5. Obtener una muestra de rangos definidos usando **.iloc**

In [12]:
pokemon_100_to_200 = pokemon.iloc[100:200]
pokemon_100_to_200

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
100,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
101,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
102,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
103,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
104,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False
196,179,Mareep,Electric,NaN,280,55,40,40,65,45,35,2,False
197,180,Flaaffy,Electric,NaN,365,70,55,55,80,60,45,2,False
198,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
199,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False

6. Como saber las columnas o atributos tiene un dataframe

In [13]:
pokemon.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

Campo Descripcion <br>
**#** El ID o numero de identificacion del Pokemo
**Name:** El nombre del Pokémon <br>
**Type 1:** Se refiere a las partes elementales (tipos) asociados tanto al Pokémon como a sus movimientos. <br>
**Type 2:** Los Pokémon pueden tener hasta 2 tipos (Pokémon de tipo dual); los movimientos solo pueden tener uno. <br>
**Total:** Representa la suma de todos los stats, lo que te da una idea de qué tan “pesado” o fuerte es el Pokémon. <br>
**HP** (Puntos de Salud): Es qué tanto aguante tiene un Pokémon antes de que lo dejen fuera de combate (se desmaya). <br>
**Attack:** La fuerza física de los ataques del Pokémon. <br>
**Defense:** Qué tanto aguanta el Pokémon contra los ataques físicos del rival. <br>
**Sp. Atk:** Ataque Especial; el poder de los movimientos especiales del Pokémon. <br>
**Sp. Def:** Defensa Especial; qué tan resistente es el Pokémon ante los ataques especiales. <br>
**Speed** (Velocidad): El Pokémon que tenga más velocidad ataca primero. <br>
**Generations:** Se refiere a la generación de la serie de juegos a la que pertenece. <br>
**Legendary:** Indica si el Pokémon es Legendario o no (son bichos muy raros y poderosos). Es un valor booleano (sí/no). <br>

7. Explorar la composicion y ausencia de datos (METADATA) con **.info**

La libreria de pandas, incluye un metodo que nos permite el tipo de datos y ausencia

In [14]:
pokemon.info

<bound method DataFrame.info of        #                 Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1            Bulbasaur    Grass  Poison    318  45      49       49
1      1            Bulbasaur    Grass  Poison    318  45      49       49
2      1            Bulbasaur    Grass  Poison    318  45      49       49
3      2              Ivysaur    Grass  Poison    405  60      62       63
4      2              Ivysaur    Grass  Poison    405  60      62       63
..   ...                  ...      ...     ...    ...  ..     ...      ...
798  719              Diancie     Rock   Fairy    600  50     100      150
799  719  DiancieMega Diancie     Rock   Fairy    700  50     160      110
800  720  HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
801  720   HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
802  721            Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
0         65       65     45           1      False
1         65       65     45           1      False
2         65       65     45           1      False
3         80       80     60           1      False
4         80       80     60           1       True
..       ...      ...    ...         ...        ...
798      100      150     50           6       True
799      160      110    110           6       True
800      150      130     70           6       True
801      170      130     80           6       True
802      130       90     70           6       True

[803 rows x 13 columns]>

8. Limpieza de datos

Dependiendo del objeto del análisis algunas columnas o registro no serán necesarias en nuestro Dataframe, en este caso omitiremos los datos vacios, por los que eliminaremos la columna 'Type 2', y renombraremos la columna 'Type 1' por 'Type'.

In [15]:
del pokemon['Type 2']
pokemon.rename(columns={'Type 1':'Type'}, inplace= True)

pokemon

**Ejercicio 02** Consulta la Metadata de la actualización y compara los cambios con la anterior.

In [16]:
pokemon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           803 non-null    int64
 1   Name        803 non-null    object
 2   Type        803 non-null    object
 3   Total       803 non-null    int64
 4   HP          803 non-null    int64
 5   Attack      803 non-null    int64
 6   Defense     803 non-null    int64
 7   Sp. Atk     803 non-null    int64
 8   Sp. Def     803 non-null    int64
 9   Speed       803 non-null    int64
 10  Generation  803 non-null    int64
 11  Legendary   803 non-null    bool
dtypes: bool(1), int64(9), object(2)
memory usage: 69.9+ KB

**¿Que cambios vez?** Cambia el número de columnas del Dataframe. Esto se puede corroborar viendo el contador de la primera columna; el último numero es 11, cuando antes era 12. Igual la columna 'Type' es un renombre de la anterior llamada 'Type 1'. La columna 'Type 2' desaparecio.

9. Visualizacion de los primeros datos usando el metodo **.head**

In [18]:
pokemon.head()

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
1,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
2,1,Bulbasaur,Grass,318,45,49,49,65,65,45,1,False
3,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,False
4,2,Ivysaur,Grass,405,60,62,63,80,80,60,1,True

**Ejercicio 03** Muestra los ultimos 10 registros del dataframe

In [19]:
pokemon.tail(10)

,#,Name,Type,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
793,714,Noibat,Flying,245,40,30,35,45,40,55,6,False
794,715,Noivern,Flying,535,85,70,80,97,80,123,6,False
795,716,Xerneas,Fairy,680,126,131,95,131,98,99,6,True
796,717,Yveltal,Dark,680,126,131,95,131,98,99,6,True
797,718,Zygarde50% Forme,Dragon,600,108,100,121,81,95,95,6,True
798,719,Diancie,Rock,600,50,100,150,100,150,50,6,True
799,719,DiancieMega Diancie,Rock,700,50,160,110,160,110,110,6,True
800,720,HoopaHoopa Confined,Psychic,600,80,110,60,150,130,70,6,True
801,720,HoopaHoopa Unbound,Psychic,680,80,160,60,170,130,80,6,True
802,721,Volcanion,Fire,600,80,110,120,130,90,70,6,True

10. Estadistica basudaca del dataframe

Pandas permite emitir un reporte de estadística básica (medidas de tendencia) sobre datos cuantitativos usando el comando **.describe.**

In [33]:
pokemon.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

11. Calcular el total de datos no puplicados (unicos) <br>
Usaremos **.len()** como funcion para calcular la longitud del dataset y **unique** para excluir los duplicados

 ***NOTA:*** No conciderar ID como un atributo de llave primaria, sino el total de columnas con un solo elemento u objeto.

Obteniendo los valores unicos por columna en este caso en la comlumna "Name"

In [58]:
len(pokemon.Name.unique())

800

Obteniendo el total de objetos (Conjunto de atributos, estrictamente iguales) , unicos

In [60]:
total_unicos = len(pokemon.drop_duplicates())
total_unicos

801

**Ejercicio 04** Obtener el total de IDs unicos en el dataset

In [24]:
len(pokemon["#"].unique())

721

**Ejercicios 05:** Obtener el total tipos unicos de pokemon

In [26]:
len(pokemon.Type.unique())

18

12. Contabilizacion de Datos por Atributo

 Pandas nos permite agrupar los datos por atributos y contabilizar los totales usando .value_counts() <br>
¿Cuantos Pokemones hay por generaciom?

In [73]:
pokemon['Generation'].value_counts()

Generation
1    169
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64