# Práctica 07
## Pronóstico de Riesgo de Infarto en los Próximos 6 Meses en Xicotepec de Juárez

### Objetivo

Desarrollar un modelo de aprendizaje supervisado para predecir el nivel de riesgo de infarto en pacientes del municipio de Xicotepec de Juárez utilizando variables clínicas, demográficas y geográficas contenidas en un dataset simulado.

In [1]:
# ==========================================
# Importación de librerías
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

Cargar el dataset

In [2]:
# ==========================================
# Cargar dataset
# ==========================================

df = pd.read_csv("dataset_unificado.csv")

print("Dataset cargado correctamente.")

Dataset cargado correctamente.

Pimeros registros

In [3]:
df.head()

,ID_Paciente,CURP,Nombre,Apellido_Paterno,Apellido_Materno,Fecha_Nacimiento,Edad,Sexo,Estatura_m,Peso_kg,...,Frecuencia_Cardiaca,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar,Municipio,Region,Latitud,Longitud
0,PUE-000001,DAGA990414HPLÍÓLA5,Alejandro,Díaz,Gómez,1999-04-14,27,Masculino,1.797,70.9,...,96.0,NaN,NaN,NaN,NaN,NaN,Izúcar de Matamoros,NaN,NaN,NaN
1,PUE-000002,ROJP570110MPLDMTA8,Patricia,Rodríguez,Jiménez,1957-01-10,69,Femenino,1.460,61.9,...,81.0,NaN,NaN,NaN,NaN,NaN,San Pedro Cholula,NaN,NaN,NaN
2,PUE-000003,FOJJ020629HPLLMVA6,Javier Miguel,Flores,Jiménez,2002-06-29,23,Masculino,1.763,77.2,...,66.0,NaN,NaN,NaN,NaN,NaN,Chalchicomula de Sesma,NaN,NaN,NaN
3,PUE-000004,CUGS000111MPLRTFA8,Sofia Patricia,Cruz,Gutiérrez,2000-01-11,26,Femenino,1.522,48.7,...,73.0,NaN,NaN,NaN,NaN,NaN,Cuautlancingo,NaN,NaN,NaN
4,PUE-000005,LERA620215MPLÓMNA7,Ana Leticia,López,Ramírez,1962-02-15,64,Femenino,1.595,48.7,...,85.0,NaN,NaN,NaN,NaN,NaN,Chiautla,NaN,NaN,NaN

Últimos registros

In [4]:
df.tail()

,ID_Paciente,CURP,Nombre,Apellido_Paterno,Apellido_Materno,Fecha_Nacimiento,Edad,Sexo,Estatura_m,Peso_kg,...,Frecuencia_Cardiaca,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar,Municipio,Region,Latitud,Longitud
25499,4996,NaN,NaN,NaN,NaN,NaN,28,Masculino,1.49,49.8,...,61.0,NaN,NaN,NaN,NaN,No,NaN,NaN,18.565293,-97.502500
25500,4997,NaN,NaN,NaN,NaN,NaN,58,Femenino,1.79,73.8,...,82.0,NaN,NaN,NaN,NaN,No,NaN,NaN,18.641115,-98.501829
25501,4998,NaN,NaN,NaN,NaN,NaN,26,Masculino,1.78,55.2,...,85.0,NaN,NaN,NaN,NaN,No,NaN,NaN,19.105822,-98.264438
25502,4999,NaN,NaN,NaN,NaN,NaN,63,Masculino,1.65,86.9,...,118.0,NaN,NaN,NaN,NaN,No,NaN,NaN,19.130880,-98.285135
25503,5000,NaN,NaN,NaN,NaN,NaN,60,Femenino,1.50,56.3,...,114.0,NaN,NaN,NaN,NaN,Sí,NaN,NaN,20.188140,-97.966686

Dimensiones

In [5]:
print("Número de filas:", df.shape[0])
print("Número de columnas:", df.shape[1])

Número de filas: 25504
Número de columnas: 25

Información general

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25504 entries, 0 to 25503
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_Paciente           25504 non-null  object
 1   CURP                  5500 non-null   object
 2   Nombre                10501 non-null  object
 3   Apellido_Paterno      5501 non-null   object
 4   Apellido_Materno      5501 non-null   object
 5   Fecha_Nacimiento      5501 non-null   object
 6   Edad                  25500 non-null  object
 7   Sexo                  25500 non-null  object
 8   Estatura_m            25500 non-null  float64
 9   Peso_kg               25500 non-null  object
 10  IMC                   25500 non-null  object
 11  Presion_Sistolica     25500 non-null  object
 12  Presion_Diastolica    20500 non-null  object
 13  Glucosa               15000 non-null  float64
 14  Colesterol            15000 non-null  float64
 15  Frecuencia_Cardiaca   15500 non-null  float64
 16  Diabetes              5000 non-null   float64
 17  Hipertension          5000 non-null   float64
 18  Fumador               10000 non-null  object
 19  Actividad_Fisica      10000 non-null  object
 20  Antecedente_Familiar  10000 non-null  object
 21  Municipio             5500 non-null   object
 22  Region                0 non-null      float64
 23  Latitud               20000 non-null  float64
 24  Longitud              20000 non-null  float64
dtypes: float64(9), object(16)
memory usage: 4.9+ MB