# Práctica 07
## Pronóstico de Riesgo de Infarto en los Próximos 6 Meses en Xicotepec de Juárez

### Objetivo

Desarrollar un modelo de aprendizaje supervisado para predecir el nivel de riesgo de infarto en pacientes del municipio de Xicotepec de Juárez utilizando variables clínicas, demográficas y geográficas contenidas en un dataset simulado.

In [20]:
# ==========================================
# Importación de librerías
# ==========================================

import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

Cargar el dataset

In [21]:
# ==========================================
# Cargar dataset
# ==========================================

df = pd.read_csv("dataset_unificado.csv")

print("Dataset cargado correctamente.")

Dataset cargado correctamente.

Pimeros registros

In [22]:
df.head()

,ID_Paciente,CURP,Nombre,Apellido_Paterno,Apellido_Materno,Fecha_Nacimiento,Edad,Sexo,Estatura_m,Peso_kg,...,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar,Municipio,Region,Latitud,Longitud,Riesgo_Infarto
0,PAC-00001,RORL681104HPL2UTXE,Luis,Rodriguez,Ramirez,1968-11-04,58,M,1.64,72.4,...,0,1,0,0,1,Xicotepec de Juárez,Sierra Norte,20.25676,-97.92826,Alto
1,PAC-00002,REVP730124MPLO28WX,Patricia,Reyes,Vazquez,1973-01-24,53,F,1.69,88.5,...,0,0,0,1,1,Xicotepec de Juárez,Sierra Norte,20.30251,-97.94065,Medio
2,PAC-00003,LOJS840508MPLLYO76,Sofia,Lopez,Jimenez,1984-05-08,42,F,1.64,83.9,...,0,1,0,0,1,Xicotepec de Juárez,Sierra Norte,20.30936,-97.99931,Alto
3,PAC-00004,RERE740405MPL1YFGU,Elena,Reyes,Reyes,1974-04-05,52,F,1.69,71.1,...,0,0,0,0,0,Ajalpan,Otras Regiones,18.60916,-97.60045,Medio
4,PAC-00005,SASJ851204HPLQGQ9A,Jose,Sanchez,Sanchez,1985-12-04,41,M,1.73,79.1,...,0,0,0,1,0,Puebla,Otras Regiones,19.43582,-98.14650,Bajo

Últimos registros

In [23]:
df.tail()

,ID_Paciente,CURP,Nombre,Apellido_Paterno,Apellido_Materno,Fecha_Nacimiento,Edad,Sexo,Estatura_m,Peso_kg,...,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar,Municipio,Region,Latitud,Longitud,Riesgo_Infarto
24995,PAC-24996,CRRA670524HPLVXS0E,Antonio,Cruz,Reyes,1967-05-24,59,M,1.70,75.8,...,0,1,0,0,0,Puebla,Otras Regiones,18.74856,-98.34042,Alto
24996,PAC-24997,GOGG920815MPLUGOUH,Guadalupe,Gonzalez,Gomez,1992-08-15,34,F,1.69,70.8,...,1,0,0,0,0,Zacatlán,Otras Regiones,19.05184,-97.58758,Medio
24997,PAC-24998,VAPI520219MPLP4G99,Isabel,Vazquez,Perez,1952-02-19,74,F,1.49,51.8,...,0,1,0,1,0,Puebla,Otras Regiones,19.16549,-98.03477,Alto
24998,PAC-24999,RESS600930MPLAWBV0,Sofia,Reyes,Sanchez,1960-09-30,66,F,1.68,76.4,...,0,1,1,1,0,Xicotepec de Juárez,Sierra Norte,20.27487,-97.97501,Alto
24999,PAC-25000,HEPI710917MPLYIPYK,Isabel,Hernandez,Perez,1971-09-17,55,F,1.72,92.7,...,0,1,0,0,1,Puebla,Otras Regiones,18.67228,-98.16746,Alto

Dimensiones

In [24]:
print("Número de filas:", df.shape[0])
print("Número de columnas:", df.shape[1])

Número de filas: 25000
Número de columnas: 26

Información general

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_Paciente           25000 non-null  object
 1   CURP                  25000 non-null  object
 2   Nombre                25000 non-null  object
 3   Apellido_Paterno      25000 non-null  object
 4   Apellido_Materno      25000 non-null  object
 5   Fecha_Nacimiento      25000 non-null  object
 6   Edad                  25000 non-null  int64
 7   Sexo                  25000 non-null  object
 8   Estatura_m            25000 non-null  float64
 9   Peso_kg               25000 non-null  float64
 10  IMC                   25000 non-null  float64
 11  Presion_Sistolica     25000 non-null  int64
 12  Presion_Diastolica    25000 non-null  int64
 13  Glucosa               25000 non-null  int64
 14  Colesterol            25000 non-null  int64
 15  Frecuencia_Cardiaca   25000 non-null  int64
 16  Diabetes              25000 non-null  int64
 17  Hipertension          25000 non-null  int64
 18  Fumador               25000 non-null  int64
 19  Actividad_Fisica      25000 non-null  int64
 20  Antecedente_Familiar  25000 non-null  int64
 21  Municipio             25000 non-null  object
 22  Region                25000 non-null  object
 23  Latitud               25000 non-null  float64
 24  Longitud              25000 non-null  float64
 25  Riesgo_Infarto        25000 non-null  object
dtypes: float64(5), int64(11), object(10)
memory usage: 5.0+ MB

Tipos de datos

In [26]:
df.dtypes.to_frame("Tipo de dato")

                     Tipo de dato
ID_Paciente                object
CURP                       object
Nombre                     object
Apellido_Paterno           object
Apellido_Materno           object
Fecha_Nacimiento           object
Edad                        int64
Sexo                       object
Estatura_m                float64
Peso_kg                   float64
IMC                       float64
Presion_Sistolica           int64
Presion_Diastolica          int64
Glucosa                     int64
Colesterol                  int64
Frecuencia_Cardiaca         int64
Diabetes                    int64
Hipertension                int64
Fumador                     int64
Actividad_Fisica            int64
Antecedente_Familiar        int64
Municipio                  object
Region                     object
Latitud                   float64
Longitud                  float64
Riesgo_Infarto             object

Valores faltantes

In [27]:
valores_nulos = df.isnull().sum().sort_values(ascending=False)

valores_nulos.to_frame("Valores nulos")

                      Valores nulos
ID_Paciente                       0
CURP                              0
Longitud                          0
Latitud                           0
Region                            0
Municipio                         0
Antecedente_Familiar              0
Actividad_Fisica                  0
Fumador                           0
Hipertension                      0
Diabetes                          0
Frecuencia_Cardiaca               0
Colesterol                        0
Glucosa                           0
Presion_Diastolica                0
Presion_Sistolica                 0
IMC                               0
Peso_kg                           0
Estatura_m                        0
Sexo                              0
Edad                              0
Fecha_Nacimiento                  0
Apellido_Materno                  0
Apellido_Paterno                  0
Nombre                            0
Riesgo_Infarto                    0

Porcentajes nulos

In [28]:
porcentaje_nulos = (df.isnull().sum()/len(df))*100

porcentaje_nulos.sort_values(ascending=False).round(2)

ID_Paciente             0.0
CURP                    0.0
Longitud                0.0
Latitud                 0.0
Region                  0.0
Municipio               0.0
Antecedente_Familiar    0.0
Actividad_Fisica        0.0
Fumador                 0.0
Hipertension            0.0
Diabetes                0.0
Frecuencia_Cardiaca     0.0
Colesterol              0.0
Glucosa                 0.0
Presion_Diastolica      0.0
Presion_Sistolica       0.0
IMC                     0.0
Peso_kg                 0.0
Estatura_m              0.0
Sexo                    0.0
Edad                    0.0
Fecha_Nacimiento        0.0
Apellido_Materno        0.0
Apellido_Paterno        0.0
Nombre                  0.0
Riesgo_Infarto          0.0
dtype: float64

Estadísticas descriptivas

In [30]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID_Paciente,25000,25000,PAC-00001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CURP,25000,25000,RORL681104HPL2UTXE,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Nombre,25000,20,Laura,1329,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Apellido_Paterno,25000,16,Martinez,1632,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Apellido_Materno,25000,16,Sanchez,1627,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fecha_Nacimiento,25000,14403,1982-10-05,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Edad,25000.0,NaN,NaN,NaN,51.49648,14.742815,18.0,41.0,52.0,62.0,90.0
Sexo,25000,2,F,12806,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Estatura_m,25000.0,NaN,NaN,NaN,1.650156,0.079955,1.29,1.6,1.65,1.7,1.96
Peso_kg,25000.0,NaN,NaN,NaN,71.002048,12.884441,29.0,62.1,70.4,79.3,131.0
IMC,25000.0,NaN,NaN,NaN,26.016224,3.985415,10.9,23.3,26.0,28.7,42.8
Presion_Sistolica,25000.0,NaN,NaN,NaN,132.57768,10.499946,90.0,125.0,133.0,140.0,175.0
Presion_Diastolica,25000.0,NaN,NaN,NaN,84.82404,7.189266,55.0,80.0,85.0,90.0,113.0
Glucosa,25000.0,NaN,NaN,NaN,97.46104,25.096586,-11.0,80.0,97.0,114.0,190.0
Colesterol,25000.0,NaN,NaN,NaN,194.78204,35.216226,42.0,171.0,195.0,219.0,339.0
Frecuencia_Cardiaca,25000.0,NaN,NaN,NaN,71.5382,8.040781,41.0,66.0,71.0,77.0,103.0
Diabetes,25000.0,NaN,NaN,NaN,0.16484,0.371044,0.0,0.0,0.0,0.0,1.0
Hipertension,25000.0,NaN,NaN,NaN,0.42744,0.494717,0.0,0.0,0.0,1.0,1.0
Fumador,25000.0,NaN,NaN,NaN,0.25004,0.433044,0.0,0.0,0.0,1.0,1.0
Actividad_Fisica,25000.0,NaN,NaN,NaN,0.40348,0.490605,0.0,0.0,0.0,1.0,1.0
Antecedente_Familiar,25000.0,NaN,NaN,NaN,0.30032,0.458406,0.0,0.0,0.0,1.0,1.0
Municipio,25000,6,Xicotepec de Juárez,9918,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,25000,2,Sierra Norte,14987,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitud,25000.0,NaN,NaN,NaN,19.746494,0.641455,18.50003,19.118807,20.174115,20.27618,20.31998
Longitud,25000.0,NaN,NaN,NaN,-97.993866,0.187472,-98.49991,-98.061975,-97.98226,-97.935767,-97.50008
Riesgo_Infarto,25000,4,Medio,11148,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
for columna in df.columns:
    print(columna)

ID_Paciente
CURP
Nombre
Apellido_Paterno
Apellido_Materno
Fecha_Nacimiento
Edad
Sexo
Estatura_m
Peso_kg
IMC
Presion_Sistolica
Presion_Diastolica
Glucosa
Colesterol
Frecuencia_Cardiaca
Diabetes
Hipertension
Fumador
Actividad_Fisica
Antecedente_Familiar
Municipio
Region
Latitud
Longitud
Riesgo_Infarto

Municipios disponibles

In [32]:
df["Municipio"].value_counts()

Municipio
Xicotepec de Juárez    9918
Huauchinango           5069
Zacatlán               3727
Puebla                 2589
Teziutlán              2548
Ajalpan                1149
Name: count, dtype: int64

Filtrar Xicotepec

In [35]:
df_xico = df[df["Municipio"] == "Xicotepec de Juárez"].copy()

print(f"Pacientes de Xicotepec: {len(df_xico)}")

Pacientes de Xicotepec: 9918

In [36]:
df_xico.head()

,ID_Paciente,CURP,Nombre,Apellido_Paterno,Apellido_Materno,Fecha_Nacimiento,Edad,Sexo,Estatura_m,Peso_kg,...,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar,Municipio,Region,Latitud,Longitud,Riesgo_Infarto
0,PAC-00001,RORL681104HPL2UTXE,Luis,Rodriguez,Ramirez,1968-11-04,58,M,1.64,72.4,...,0,1,0,0,1,Xicotepec de Juárez,Sierra Norte,20.25676,-97.92826,Alto
1,PAC-00002,REVP730124MPLO28WX,Patricia,Reyes,Vazquez,1973-01-24,53,F,1.69,88.5,...,0,0,0,1,1,Xicotepec de Juárez,Sierra Norte,20.30251,-97.94065,Medio
2,PAC-00003,LOJS840508MPLLYO76,Sofia,Lopez,Jimenez,1984-05-08,42,F,1.64,83.9,...,0,1,0,0,1,Xicotepec de Juárez,Sierra Norte,20.30936,-97.99931,Alto
5,PAC-00006,MAGA861124HPL1IYR8,Antonio,Martinez,Gomez,1986-11-24,40,M,1.69,71.2,...,1,1,1,0,0,Xicotepec de Juárez,Sierra Norte,20.25919,-97.94677,Alto
6,PAC-00007,CRMJ800903HPLA92VN,Juan,Cruz,Morales,1980-09-03,46,M,1.55,58.4,...,0,1,1,0,0,Xicotepec de Juárez,Sierra Norte,20.25042,-97.94491,Alto

Validar volumen

In [37]:
print("Dimensiones del nuevo dataset:")

df_xico.shape

Dimensiones del nuevo dataset:

(9918, 26)

Variables clínicas

In [38]:
variables_clinicas = [

    "Edad",
    "Estatura_m",
    "Peso_kg",
    "IMC",
    "Presion_Sistolica",
    "Presion_Diastolica",
    "Glucosa",
    "Colesterol",
    "Frecuencia_Cardiaca",
    "Diabetes",
    "Hipertension",
    "Fumador",
    "Actividad_Fisica",
    "Antecedente_Familiar"

]

df_xico[variables_clinicas].head()

,Edad,Estatura_m,Peso_kg,IMC,Presion_Sistolica,Presion_Diastolica,Glucosa,Colesterol,Frecuencia_Cardiaca,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar
0,58,1.64,72.4,26.9,147,98,87,200,69,0,1,0,0,1
1,53,1.69,88.5,31.0,119,75,74,158,71,0,0,0,1,1
2,42,1.64,83.9,31.2,142,86,110,162,78,0,1,0,0,1
5,40,1.69,71.2,24.9,130,86,158,183,61,1,1,1,0,0
6,46,1.55,58.4,24.3,130,102,77,191,65,0,1,1,0,0

In [39]:
variables_geograficas = [

    "Latitud",
    "Longitud"

]

df_xico[variables_geograficas].head()

    Latitud  Longitud
0  20.25676 -97.92826
1  20.30251 -97.94065
2  20.30936 -97.99931
5  20.25919 -97.94677
6  20.25042 -97.94491

In [41]:
df_xico.describe()  # Por defecto solo incluye las numéricas y elimina los NaN de texto

,Edad,Estatura_m,Peso_kg,IMC,Presion_Sistolica,Presion_Diastolica,Glucosa,Colesterol,Frecuencia_Cardiaca,Diabetes,Hipertension,Fumador,Actividad_Fisica,Antecedente_Familiar,Latitud,Longitud
count,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000,9918.00000,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000,9918.000000
mean,51.338879,1.650210,71.124299,26.060224,132.601432,84.795523,97.224541,194.66949,71.445150,0.161625,0.427102,0.250958,0.404719,0.294112,20.285031,-97.960495
std,14.797623,0.079668,12.911495,4.006796,10.510406,7.214621,24.776726,35.63369,8.058133,0.368125,0.494682,0.433586,0.490862,0.455665,0.020090,0.022963
min,18.000000,1.290000,30.600000,10.900000,94.000000,58.000000,8.000000,56.00000,44.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.250000,-98.000000
25%,41.000000,1.600000,62.300000,23.400000,125.000000,80.000000,81.000000,171.00000,66.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.267762,-97.980530
50%,51.000000,1.650000,70.500000,26.100000,133.000000,85.000000,97.000000,195.00000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.285215,-97.960775
75%,61.750000,1.700000,79.600000,28.800000,140.000000,90.000000,114.000000,218.00000,77.000000,0.000000,1.000000,1.000000,1.000000,1.000000,20.302230,-97.940832
max,90.000000,1.950000,131.000000,42.800000,170.000000,110.000000,181.000000,339.00000,102.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.319980,-97.920010